export const RECEIVE_POKEMON_LIST = "RECEIVE_POKEMON_LIST";
export const RECEIVE_POKEMON_DETAILS = "RECEIVE_POKEMON_DETAILS";
export const UPDATE_POKEMON_DETAILS_LOADING = "UPDATE_POKEMON_DETAILS_LOADING";
export const RECEIVE_POKEMON_EVOLUTION = "RECEIVE_POKEMON_EVOLUTION";
export const UPDATE_POKEMON_EVOLUTION_LOADING = "UPDATE_POKEMON_EVOLUTION_LOADING";